---
abstract: 'Turns ref() into a multimethod'
author:
  - 'Josh Jore <jjore@cpan.org>'
build_requires:
  Test::More: 0
  overload: 0
configure_requires:
  ExtUtils::MakeMaker: 6.31
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.200000, CPAN::Meta::Converter version 2.102400'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: UNIVERSAL-ref
requires:
  B: 0
  B::Utils: 0
  Test::More: 0
  XSLoader: 0
  perl: 5.6.2
version: 0.13
